/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';
import { UseFormReturn, useFieldArray } from 'react-hook-form';
import { MineralFormData } from '@/lib/validations/mineral';
import { FormDescription, FormField, FormItem, FormLabel, FormControl, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export function GallerySection({ form, onStorageKeyManualChange }: { form: UseFormReturn<MineralFormData>; onStorageKeyManualChange: () => void }) {
  const { fields, append, remove } = useFieldArray({ control: form.control, name: 'images.gallery' });
  const pathField = (name: string, label: string, placeholder: string, description?: string) => { const isImagePath = name.endsWith('.path'); return <FormField control={form.control} name={name as any} rules={isImagePath ? { validate: (value: string | null | undefined) => !value || !/^https?:\/\//i.test(value) || 'Укажите путь внутри папки, а не полный URL.' } : undefined} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl><Input {...field} placeholder={placeholder} value={field.value ?? ''} /></FormControl>{description && <FormDescription>{description}</FormDescription>}<FormMessage /></FormItem>} />; };
  return <Card><CardHeader><CardTitle>Изображения</CardTitle></CardHeader><CardContent className="space-y-5"><FormField control={form.control} name="images.storage_key" render={({ field }) => <FormItem><FormLabel>Папка изображений</FormLabel><FormControl><Input {...field} placeholder="kambaba_jasper" value={field.value ?? ''} onChange={event => { onStorageKeyManualChange(); field.onChange(event.target.value); }} /></FormControl><FormDescription>Имя папки этой карточки в хранилище. Используется для всех изображений камня.</FormDescription><FormMessage /></FormItem>} />{pathField('images.hero.path', 'Главное изображение', 'hero.webp', 'Путь внутри папки изображений.')}{pathField('images.thumbnail.path', 'Миниатюра', 'thumbnail.webp')}<div className="space-y-3"><div><h3 className="font-medium">Галерея</h3><p className="text-sm text-muted-foreground">Указывайте путь внутри папки изображений, например gallery/kambaba_jasper00.webp. Имя папки повторять не нужно.</p></div>{fields.map((row, index) => <section key={row.id} className="rounded border p-4 space-y-3"><div className="flex items-center justify-between gap-3"><h4 className="font-medium">Изображение галереи {index + 1}</h4><Button type="button" variant="destructive" onClick={() => remove(index)}>Удалить</Button></div>{pathField(`images.gallery.${index}.path`, 'Путь к изображению', `gallery/image-${index + 1}.webp`)}{pathField(`images.gallery.${index}.caption.ru`, 'Подпись на русском', 'Необязательно')}{pathField(`images.gallery.${index}.caption.en`, 'Caption in English', 'Optional')}</section>)}<Button type="button" variant="outline" onClick={() => append({ path: '', type: null, caption: { ru: null, en: null } })}>Добавить изображение</Button></div></CardContent></Card>;
}
