/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';
import { useState } from 'react';
import { UseFormReturn } from 'react-hook-form';
import { MineralFormData } from '@/lib/validations/mineral';
import { FormField, FormItem, FormLabel, FormControl, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
const enums: Record<string,string[]>={rarity:['common','uncommon','rare','very_rare'],base_color:['red','black','bi_color','blue','brown','green','yellow','grey','purple','white','pink','multicolor','orange'],mineral_class:['native_elements','sulfides_sulfosalts','halides','oxides_hydroxides','carbonates_nitrates','borates','sulfates_chromates_molybdates_tungstates','phosphates_arsenates_vanadates','silicates','organic'],silicate_subclass:['nesosilicates','sorosilicates','cyclosilicates','inosilicates','phyllosilicates','tectosilicates'],mineral_family:['garnet_group','feldspar_group','quartz_group','tourmaline_group','mica_group','pyroxene_group','amphibole_group','zeolite_group','beryl_group','spinel_group','corundum_group','calcite_group'],crystal_system:['monoclinic','orthorhombic','hexagonal','trigonal','isometric','triclinic','tetragonal','amorphous'],streak:['black','white_or_colourless','grey','green','blue','brown','pink_to_red','yellow_to_orange'],transparency:['transparent','translucent','opaque'],fracture:['conchoidal','uneven','splintery','hackly','earthy','fibrous'],cleavage_degree:['none','very_poor','poor','good','perfect'],cleavage_direction:['1','2','3','4'],cleavage_type:['basal','prismatic','pinacoidal','rhombohedral','cubic','octahedral','dodecahedral'],ima_status:['approved','grandfathered','questionable','discredited'],rock_type:['igneous','sedimentary','metamorphic'],crystal_habit:['prismatic','acicular','tabular','platy','foliated','fibrous','granular','massive','druzy','radiating','globular','reniform','botryoidal','columnar','cubic','rhombohedral','dendritic','earthy'],luster:['vitreous','adamantine','metallic','submetallic','pearly','silky','resinous','greasy','waxy','dull','earthy'],tenacity:['brittle','malleable','ductile','sectile','flexible','elastic'],phenomena:['asterism','iridescence','aventurescence','adularescence','labradorescence','chatoyancy','opalescence','color_change']};
function Field({form,name,label,options}:{form:UseFormReturn<MineralFormData>;name:string;label:string;options:string[]}){return <FormField control={form.control} name={name as any} render={({field})=><FormItem><FormLabel>{label}</FormLabel><Select value={field.value??''} onValueChange={v=>field.onChange(v==='__none__'?null:v)}><FormControl><SelectTrigger><SelectValue placeholder="Не указано"/></SelectTrigger></FormControl><SelectContent><SelectItem value="__none__">Не указано</SelectItem>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><FormMessage/></FormItem>}/>}
function Multi({form,name,label,options}:{form:UseFormReturn<MineralFormData>;name:string;label:string;options:string[]}){return <FormField control={form.control} name={name as any} render={({field})=><FormItem><FormLabel>{label}</FormLabel><div className="flex flex-wrap gap-2">{options.map(v=><Button type="button" variant={(field.value??[]).includes(v)?'default':'outline'} key={v} onClick={()=>field.onChange((field.value??[]).includes(v)?field.value.filter((x:string)=>x!==v):[...(field.value??[]),v])}>{v}</Button>)}</div></FormItem>}/>}
export function ScientificSection({form}:{form:UseFormReturn<MineralFormData>}){const [hard,setHard]=useState(!!form.getValues('scientific.hardness'));const [sg,setSg]=useState(!!form.getValues('scientific.specific_gravity')); const range=(kind:'hardness'|'specific_gravity',active:boolean,set:(v:boolean)=>void,min:number,step:number)=><div className="rounded border p-3 space-y-2"><div className="flex justify-between"><FormLabel>{kind==='hardness'?'Твёрдость (Моос)':'Specific gravity (безразмерная относительная плотность)'}</FormLabel><Button type="button" variant="outline" onClick={()=>{set(!active);if(active)form.setValue(`scientific.${kind}` as any,null)}}>{active?'Удалить':'Указать'}</Button></div>{active&&<div className="grid grid-cols-2 gap-3">{(['min','max'] as const).map(k=><FormField key={k} control={form.control} name={`scientific.${kind}.${k}` as any} render={({field})=><FormItem><FormLabel>{k}</FormLabel><FormControl><Input type="number" step={step} min={min} value={field.value??''} onChange={e=>field.onChange(e.target.value===''?undefined:Number(e.target.value))}/></FormControl><FormMessage/></FormItem>}/>)}</div>}</div>;
return <Card><CardHeader><CardTitle>Научные свойства</CardTitle></CardHeader><CardContent className="space-y-5">{range('hardness',hard,setHard,1,.1)}{range('specific_gravity',sg,setSg,0,.01)}<FormField control={form.control} name="scientific.chemical_formula" render={({field})=><FormItem><FormLabel>Химическая формула</FormLabel><FormControl><Input {...field} value={field.value??''}/></FormControl></FormItem>}/><div className="grid md:grid-cols-2 gap-4">{(['rarity','base_color','mineral_class','silicate_subclass','mineral_family','crystal_system','streak','transparency','fracture','cleavage_degree','cleavage_direction','cleavage_type','ima_status','rock_type'] as const).map(k=><Field key={k} form={form} name={`scientific.${k}`} label={k} options={enums[k]}/>)}</div>{(['crystal_habit','luster','tenacity','phenomena'] as const).map(k=><Multi key={k} form={form} name={`scientific.${k}`} label={k} options={enums[k]}/>)}</CardContent></Card>}
